[mailgun]
api_base_url = "https://api.mailgun.net/v3/email.b01lers.com"
email_address = "Purdue Capture The Flag Team <b01lers@b01lers.com>"

[server]
guild_id = 511675552386777099

ctf_category_id = 534524532799569950
archived_ctf_category_id = 877584240965984256
solve_approvals_channel_id = 757358907034435686
bot_log_channel = 743238600329658459
rank_up_channel = 879945978512277514

officer_role = "officer"
member_role = "members"

welcome_message = """
Welcome to B01lers!
    
The best way to get started is to come every weekend, play, and ask questions along the way to see what skills you
need as you play. If you don't know something, learn it while you work or take the next week to learn if you can't
figure it out!

At the beginning of the semester, we stream a 'bootcamp' with training content on various categories. Those were
recorded: <https://youtube.com/c/b01lers>. We highly suggest watching those in chunks and working along with the
videos. You'll notice we use a docker container....just ignore that and use Ubuntu!

We have an internal CTF server for practice too: <https://internal.b01lers.com/home>. This has challenges from our
own past CTFs and bootcamps! Ask questions in #internal-ctf about that and we will help out!

If you're interested in learning certain categories or specific skills, there are a couple good learning resources:
* Cryptography: <https://cryptohack.org/> 
* Binary Exploitation: <https://pwn.college/> 
* Web: there's no obvious winner here that I know of... :( <https://overthewire.org/wargames/natas/ is okay,
  maybe someone else has a better resource

Picoctf is an easier competition with many categories that is always on and generally really good.

Overthewire bandit is a great intro to bash and thinking like a ctfer: https://overthewire.org/wargames/bandit/ once
it starts getting really weird it becomes less useful though."""

join_dm_message = "Welcome to b01lers! To verify yourself as a Purdue University student, just type `/verify email <your-@purdue.edu-email-address-here>`"

# :blobsolute: emoji on b01lers
ctf_default_emoji_id = 1257157847612129351

[ranks]
points_per_solve = 100
points_per_message = 1

rank_names = [
    "ğŸŸ Phish Food",
    "ğŸ“œ Script Kiddie",
    "âŒ¨ï¸ /r/masterhacker",
    "</> Inspector of Elements",
    "âŒ Cross-Site Scripter",
    "ğŸ’« Path Explorer",
    "ğŸ© White Hat",
    "ğŸ› ï¸ Pwn Tool",
    "ğŸ¤« Bad Actor",
    "ğŸ£ Fuzzer Duckling",
    "ğŸ¦¦ ShellMammal",
    "ğŸ‘¾ Anti-Anti Virus",
    "ğŸ’» Not an Enigma",
    "ğŸš Shell Popper",
    "ğŸ’¸ Bounty Hunter",
    "ğŸ’¼ Edge Case",
    "ğŸ–¥ï¸ Gibson Crasher",
    "ğŸ”¥ Intrusion Creation System",
    "ğŸ¦ Zero Cool",
    "ğŸŒˆ 1337",
]